@startuml
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response

'SampleActivity -> DataProviderLoader: load(BaseDataProvider)


SampleActivity -> SampleDataProvider: DataProviderLoader.getInstance().loadData()

SampleDataProvider -> LoadDispatcherTask: getDispatcherTask()

LoadDispatcherTask -> LoadDispatcherTask: DataProviderLoader.getInstance().get(mDataProvider.getCacheKey())\n获取缓存，根据缓存模式决定使用 网络/缓存 数据

LoadDispatcherTask -> LoadNetDataTask: tryLoadNetData()

LoadNetDataTask -> LoadNetDataTask: DataProviderConfig.getNetQuestAdapter().syncRequest()\n请求网络数据

LoadNetDataTask -> SampleDataProvider:  mDataProvider.fillData()

LoadNetDataTask -> SampleDataProvider:  mDataProvider.parseData(str)

LoadNetDataTask -> LoadDispatcherTask: onLoadNetDataSuccess()

LoadNetDataTask -> LoadDispatcherTask: onLoadNetDataFailed()

LoadNetDataTask -> LoadNetDataTask: DataProviderLoader.getInstance().save()\n存入缓存


LoadDispatcherTask -> LoadDiskDataTask: tryLoadDiskData()


LoadDiskDataTask -> SampleDataProvider:  mDataProvider.fillData()

LoadDiskDataTask -> SampleDataProvider:  mDataProvider.parseData(str)

LoadDiskDataTask -> LoadDispatcherTask: onLoadDiskExpiredDataSuccess()

LoadDiskDataTask -> LoadDispatcherTask: onLoadDiskExpiredDataFailed()

LoadDispatcherTask -> SampleActivity: notifyLoadPageDataSuccess()

LoadDispatcherTask -> SampleActivity: notifyLoadPageDataFailed()

SampleActivity -> SampleActivity: 通知 Adapter 刷新

@enduml