@startuml
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response

'SampleActivity -> DataProviderLoader: load(BaseDataProvider)

SampleActivity -> SimpleDataProviderCreator: 创建

SimpleDataProviderCreator -> DataProvider: 构建 DataProvider

DataProvider -> SimpleDataProviderCreator: 构建 DataProvider

SimpleDataProviderCreator -> SampleActivity: provider

SampleActivity -> DataProvider:provider.loadData()

DataProvider -> SimpleProviderLoader : loadData()



SimpleProviderLoader -> LoadDispatcherTask: getDispatcherTask()

LoadDispatcherTask -> LoadDispatcherTask: 获取缓存，根据缓存模式决定\n 使用 网络/缓存 数据

LoadDispatcherTask -> LoadNetDataTask: tryLoadNetData()

LoadNetDataTask -> LoadNetDataTask: DataProviderConfig.getNetQuestAdapter().syncRequest()\n请求网络数据

LoadNetDataTask -> DataProvider:  mDataProvider.fillData()

LoadNetDataTask -> DataProvider:  mDataProvider.parseData(str)

LoadNetDataTask -> LoadDispatcherTask: onLoadNetDataSuccess()

LoadNetDataTask -> LoadDispatcherTask: onLoadNetDataFailed()

LoadNetDataTask -> LoadNetDataTask: DataProviderLoader.getInstance().save()\n存入缓存


LoadDispatcherTask -> LoadDiskDataTask: tryLoadDiskData()


LoadDiskDataTask -> DataProvider:  mDataProvider.fillData()

LoadDiskDataTask -> DataProvider:  mDataProvider.parseData(str)

LoadDiskDataTask -> LoadDispatcherTask: onLoadDiskExpiredDataSuccess()

LoadDiskDataTask -> LoadDispatcherTask: onLoadDiskExpiredDataFailed()

LoadDispatcherTask -> SimpleProviderLoader: onLoadDiskExpiredDataSuccess()

LoadDispatcherTask -> SimpleProviderLoader: onLoadDiskExpiredDataFailed()

SimpleProviderLoader -> SampleActivity: notifyLoadPageDataSuccess()

SimpleProviderLoader -> SampleActivity: notifyLoadPageDataFailed()

SampleActivity -> SampleActivity: 通知 Adapter 刷新

@enduml