@startuml
'Alice -> Bob: Authentication Request
'Bob --> Alice: Authentication Response
'
'Alice -> Bob: Another authentication Request
'Alice <-- Bob: another authentication Response


SampleActivity -> Zebra: Zebra.with(SampleResponseBean.class)\n    .url(url)\n    .viewBindItemBuilder(new SampleViewBindItemBuilder())\n    .cacheConfig(cacheMode, new SampleGetExpiredTime())\n    .load()\n    .observe(this, this);

SampleActivity -> SimpleProviderLoader : load()

SimpleProviderLoader -> LoadDispatcherTask: getDispatcherTask()

LoadDispatcherTask -> LoadDispatcherTask: 获取缓存，根据缓存模式决定\n 使用 网络/缓存 数据

LoadDispatcherTask -> LoadNetDataTask: tryLoadNetData()

LoadNetDataTask -> LoadNetDataTask: ZebraConfig.getNetQuestAdapter().syncRequest()\n请求网络数据

LoadNetDataTask -> Zebra:  mZebra.parseData()

LoadNetDataTask -> Zebra:  mZebra.buildViewBindItem()

LoadNetDataTask -> LoadDispatcherTask: onLoadNetDataSuccess()

LoadNetDataTask -> LoadDispatcherTask: onLoadNetDataFailed()

LoadNetDataTask -> LoadNetDataTask: CacheController.getInstance().save()\n存入缓存


LoadDispatcherTask -> LoadDiskDataTask: tryLoadDiskData()


LoadDiskDataTask -> Zebra:  mZebra.parseData()

LoadDiskDataTask -> Zebra:  mZebra.buildViewBindItem()

LoadDiskDataTask -> LoadDispatcherTask: onLoadDiskExpiredDataSuccess()

LoadDiskDataTask -> LoadDispatcherTask: onLoadDiskExpiredDataFailed()

LoadDispatcherTask -> SimpleProviderLoader: onLoadDiskExpiredDataSuccess()

LoadDispatcherTask -> SimpleProviderLoader: onLoadDiskExpiredDataFailed()

SimpleProviderLoader -> SampleActivity: notifyLoadPageDataSuccess()

SimpleProviderLoader -> SampleActivity: notifyLoadPageDataFailed()

SampleActivity -> SampleActivity: 通知 Adapter 刷新

@enduml